spring:
  application:
    name: test-cloud-test1
  profiles:
    active: dev
    
  profiles: dev
  application:
    name: test-cloud-test1-dev
    
  profiles: test
  application:
    name: test-cloud-test1-test
    

