spring:
  application:
    name: test-cloud-test1
  profiles:
    active: dev
    
...

spring:    
  profiles: dev
  application:
    name: test-cloud-test1-dev
   
 ...
 spring:
  profiles: test
  application:
    name: test-cloud-test1-test
    

